spring:
  datasource:
    url: 'jdbc:h2:mem:db'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''
    hikari:
      connection-test-query: 'SELECT 1'
      connection-init-sql: "RUNSCRIPT FROM 'src/main/resources/init.sql'"
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
  h2:
    console:
      enabled: true